[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "http://thesmile.me"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"
